version: "3.9"

services:

  postgres:

    image: postgres:16

    restart: always

    environment:

      POSTGRES_USER: sentinel

      POSTGRES_PASSWORD: sentinel

      POSTGRES_DB: sentinelx

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data: